// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// set_attr
void set_attr(SEXP x, SEXP attr, SEXP value);
RcppExport SEXP refer_set_attr(SEXP xSEXP, SEXP attrSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type attr(attrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type value(valueSEXP);
    set_attr(x, attr, value);
    return R_NilValue;
END_RCPP
}
// set_class
void set_class(SEXP x, SEXP value);
RcppExport SEXP refer_set_class(SEXP xSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type value(valueSEXP);
    set_class(x, value);
    return R_NilValue;
END_RCPP
}
// set_names
void set_names(SEXP x, SEXP value);
RcppExport SEXP refer_set_names(SEXP xSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type value(valueSEXP);
    set_names(x, value);
    return R_NilValue;
END_RCPP
}
// add_class
void add_class(SEXP x, std::string value);
RcppExport SEXP refer_add_class(SEXP xSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type value(valueSEXP);
    add_class(x, value);
    return R_NilValue;
END_RCPP
}
// remove_class
void remove_class(SEXP x, std::string value);
RcppExport SEXP refer_remove_class(SEXP xSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type value(valueSEXP);
    remove_class(x, value);
    return R_NilValue;
END_RCPP
}
