# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_attr <- function(x, attr, value) {
    invisible(.Call('refer_set_attr', PACKAGE = 'refer', x, attr, value))
}

set_class <- function(x, value) {
    invisible(.Call('refer_set_class', PACKAGE = 'refer', x, value))
}

set_names <- function(x, value) {
    invisible(.Call('refer_set_names', PACKAGE = 'refer', x, value))
}

add_class <- function(x, value) {
    invisible(.Call('refer_add_class', PACKAGE = 'refer', x, value))
}

remove_class <- function(x, value) {
    invisible(.Call('refer_remove_class', PACKAGE = 'refer', x, value))
}

